# Generated by Django 3.1.7 on 2021-04-14 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='很懒的一个用户', max_length=128)),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=0)),
                ('age', models.CharField(default='0', max_length=3)),
                ('phone', models.CharField(default='1234566', max_length=11)),
                ('address', models.CharField(default='用户很懒，没填写地址', max_length=256)),
                ('abstract', models.TextField(default='用户很懒，没有描述')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
