# Generated by Django 3.1.7 on 2021-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='author',
            new_name='banzhu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='banzhu',
            new_name='author',
        ),
    ]
