# Generated by Django 3.1.7 on 2021-04-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='author',
        ),
    ]
