# Generated by Django 3.1.7 on 2021-04-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_remove_likes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='create_time',
        ),
    ]
